swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
      <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><select><template><img src=x onerror=alert(1)></template></select>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
