swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
  <select><template><img src=x onerror=prompt(1)></template></select>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
