swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    `<svg><annotation-xml><foreignobject><textarea><!--</textarea><p id="--><img src='x' onerror='alert(1)'>">`, {CUSTOM_ELEMENT_HANDLING: {tagNameCheck: /.*/},FORBID_CONTENTS: [""]}
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
